### ISSUE TITLE
Noetic problems on rviz run

### ISSUE THREAD

**Issue by raffaelemancino** [innokrobotics/innok_heros_description#1]
Using noetic distro the xacros file have a lot of  unsatisfied params.

![image](https://user-images.githubusercontent.com/9502616/116292514-1558b480-a796-11eb-9bc1-3e2dc9c15905.png)

**Comment by tobias-griepentrog** [comment]
hi @raffaelemancino, thanks for reporting this issue.
They seem to have made some changes to the xacro property scope in the recent xacro release.
The latest commit of innok_heros_description/noetic includes the property definition in the respective file scope which should fix your problem.
Closing this for now, but feel free to reopen this ticket should you still encounter the error.

**Comment by raffaelemancino** [comment]
now it works, thank you all
